name: Update Submodules
on:
  workflow_dispatch:
  schedule:
    - cron: '45 23 * * *'

concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: true

jobs:
  update-submodule:
    name: Update Submodules
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write
      
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          submodules: recursive

      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit Changes
        id: commit
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add --all
          git commit -m "Update Submodules"
    
      - name: Push Changes
        run: |
          git push
